version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: npm test
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Build project artifact
          command: npm run build
      - store_artifacts:
          path: dist/
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy to production
          command: './deploy.sh'
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build